[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "FRAME pallet template for defining custom runtime logic."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "sponsored-pool"
publish = false
repository = "https://github.com/cryptoviet/gafi"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
]}
serde = {version = "1.0.119"}

# Substrate
frame-benchmarking = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0", optional = true}
frame-support = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
frame-system = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
gafi-primitives = {default-features = false, version = "4.0.0-dev", path = "../../primitives"}
pallet-randomness-collective-flip = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
scale-info = {version = "2.1.0", default-features = false, features = ["derive"]}
sp-io = {default-features = false, version = "6.0.0", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
pallet-balances = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}

[dev-dependencies]
sp-core = {default-features = false, version = "6.0.0", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
sp-io = {default-features = false, version = "6.0.0", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
sp-runtime = {default-features = false, version = "6.0.0", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
pallet-timestamp = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "gafi-dot-v1.1.0"}
staking-pool = { default-features = false, version = "4.0.0-dev", path = "../staking-pool" }
upfront-pool = { default-features = false, version = "4.0.0-dev", path = "../upfront-pool" }
pallet-pool = { default-features = false, version = "4.0.0-dev", path = "../pool" }

[features]
default = ["std"]
std = [
  "codec/std",
  "serde/std",
  "scale-info/std",
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking/std",
  "gafi-primitives/std",
  "pallet-randomness-collective-flip/std",
  "sp-io/std",
  "pallet-balances/std",
  "upfront-pool/std",
  "pallet-pool/std",
]

runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
