[package]
name = "testnet-runtime"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.5.0", default-features = false, features = [
	"derive",
] }
log = { version = "0.4.19", default-features = false }

pallet-aura = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
pallet-grandpa = { workspace = true, default-features = false }
pallet-sudo = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-try-runtime = { workspace = true, default-features = false, optional = true }
pallet-timestamp = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }
frame-executive = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sp-block-builder = { workspace = true, default-features = false }
sp-consensus-aura = { workspace = true, default-features = false }
sp-consensus-grandpa = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-inherents = { workspace = true, default-features = false }
sp-offchain = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-session = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-transaction-pool = { workspace = true, default-features = false }
sp-version = { workspace = true, default-features = false }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { workspace = true, default-features = false }
pallet-transaction-payment-rpc-runtime-api = { workspace = true, default-features = false }

# Polkadot
polkadot-runtime-common = { workspace = true, default-features = false }

# Support Dependencies
pallet-insecure-randomness-collective-flip = { workspace = true, default-features = false }
pallet-nfts = { default-features = false, workspace = true }

# Local Dependencies
pallet-template = { version = "4.0.0-dev", default-features = false, path = "../../pallets/template" }
gafi-support = { version = "4.0.0-dev", default-features = false, path = "../../support" }
pallet-cache = { version = "4.0.0-dev", default-features = false, path = "../../pallets/pallet-cache" }
pallet-faucet = { version = "4.0.0-dev", default-features = false, path = "../../pallets/pallet-faucet" }
oracle-randomness = { version = "4.0.0-dev", default-features = false, path = "../../game/oracle-randomness" }
pallet-game = { version = "4.0.0-dev", default-features = false, path = "../../game/pallet-game" }

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
	# Substrate
	"frame-try-runtime?/std",
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"log/std",

	# Polkadot
	"polkadot-runtime-common/std",

	# Support runtime
	"pallet-insecure-randomness-collective-flip/std",
	"pallet-nfts/std",

	# Local
	"pallet-template/std",
	"gafi-support/std",
	"pallet-cache/std",
	"pallet-faucet/std",
	"oracle-randomness/std",
	"pallet-game/std",
]

try-runtime = [
	"frame-try-runtime/try-runtime",
	"frame-executive/try-runtime",
	"frame-system/try-runtime",
	"frame-support/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-template/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",

	"pallet-nfts/try-runtime",

	"gafi-support/try-runtime",
	"pallet-template/try-runtime",
	"pallet-cache/try-runtime",
	"pallet-faucet/try-runtime",
	"pallet-game/try-runtime",
	"oracle-randomness/try-runtime",
]
