[package]
name = "gafi-primitives"
version = "4.0.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = {package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
  "derive",
]}
scale-info = {version = "1.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.119"}

frame-support = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-runtime = {default-features = false, version = "5.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-std = {default-features = false, version = "4.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}
sp-io = {default-features = false, version = "5.0.0-dev", git = "https://github.com/cryptoviet/substrate", branch = "aur-dot"}


[features]
default = ["std"]
std = [
    "codec/std",
    "serde/std",
    "frame-support/std",
    "scale-info/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",
]
