[package]
name = "gu-ethereum"
version = "4.0.0-dev"
edition = {workspace = true}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = { version = "0.10", default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["derive"] }

sp-runtime = {workspace = true, default-features = false}
sp-io = {workspace = true, default-features = false}
sp-core = {workspace = true, default-features = false}
scale-info = {version = "2.5.0", default-features = false, features = ["derive"]}
serde = {workspace = true, features = ["derive"]}
rustc-hex = { version = "2.1.0", default-features = false }
sp-std = {version = "5.0.0", default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"}


[dev-dependencies]
hex-literal = "0.2.1"
parity-secp256k1 = {  default-features = false, version = "0.7.0", git = "https://github.com/paritytech/rust-secp256k1" }


[features]
default = ["std"]
std = [
    "sp-runtime/std",
    "sp-io/std",
    "sp-core/std",
    "sha3/std",
    "scale-info/std",
    "parity-scale-codec/std",
    "serde/std",
    "rustc-hex/std",
    "sp-std/std",
]
