[workspace]
members = [
  'node',
  'runtime',
  'utils',
  'pallets/template',
  'pallets/player',
  'pallets/option-pool',
  'pallets/staking-pool',
  'pallets/tx-handler',
  'pallets/address-mapping',
  'tests',
  'primitives',
]
[profile.release]
panic = 'unwind'

[patch.crates-io]

evm-core = {git = "https://github.com/cryptoviet/evm", branch = "master"}

ethereum = {git = "https://github.com/cryptoviet/ethereum", branch = "master"}
