[workspace]
members = [
  'node',
  'pallets/template',
  'runtime',
]
[profile.release]
panic = 'unwind'

[patch.crates-io]

evm-core = {git = "https://github.com/cryptoviet/evm", branch = "master"}

ethereum = {git = "https://github.com/cryptoviet/ethereum", branch = "master"}
