version: "3.2"

services:
  gafi:
    container_name: gafi-node
    image: grindytech/gafi-node:latest
    ports:
      - "9933:9933"
      - "30333:30333"
      - "9944:9944"
    volumes:
      - type: bind
        source: ./.local
        target: /root/.local
    command: --tmp --dev --rpc-port 9933 --ws-external --rpc-external
