[package]
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a parachain."
edition = "2021"
homepage = "https://gafi.network"
license = "Apache-2.0"
name = "gafi-chain-spec"
repository = "https://github.com/grindytech/cumulus/"
version = "0.1.0"

[dependencies]
clap = {version = "3.1", features = ["derive"]}
codec = {package = "parity-scale-codec", version = "3.0.0"}
derive_more = "0.99.2"
futures = '0.3'
hex-literal = "0.3.4"
jsonrpc-core = "18.0.0"
jsonrpsee = {version = "0.14.0", features = ["server"]}
log = "0.4.16"
serde = {version = "1.0.132", features = ["derive"]}
serde_json = "1.0.59"

# Frontier
fc-consensus = {workspace = true}
fc-db = {workspace = true}
fc-mapping-sync = {workspace = true}
fc-rpc = {workspace = true}
fc-rpc-core = {workspace = true}
fp-consensus = {workspace = true}
fp-evm = {workspace = true, default-features = false}
fp-rpc = {workspace = true}
fp-storage = {workspace = true}
pallet-ethereum = {workspace = true}
pallet-evm = {workspace = true}

# Substrate
frame-benchmarking = {workspace = true}
frame-benchmarking-cli = {workspace = true}
pallet-transaction-payment-rpc = {workspace = true}
sc-basic-authorship = {workspace = true}
sc-chain-spec = {workspace = true}
sc-cli = {workspace = true}
sc-client-api = {workspace = true}
sc-consensus = {workspace = true}
sc-consensus-aura = {workspace = true, optional = true}
sc-consensus-manual-seal = {workspace = true, optional = true}
sc-executor = {workspace = true}
sc-keystore = {workspace = true}
sc-network = {workspace = true}
sc-rpc = {workspace = true}
sc-rpc-api = {workspace = true}
sc-service = {workspace = true}
sc-telemetry = {workspace = true}
sc-tracing = {workspace = true}
sc-transaction-pool = {workspace = true}
sc-transaction-pool-api = {workspace = true}
sp-api = {workspace = true}
sp-block-builder = {workspace = true}
sp-blockchain = {workspace = true}
sp-consensus = {workspace = true}
sp-consensus-aura = {workspace = true}
sp-core = {workspace = true}
sp-inherents = {workspace = true}
sp-keystore = {workspace = true}
sp-offchain = {workspace = true}
sp-runtime = {workspace = true}
sp-session = {workspace = true}
sp-std = {workspace = true}
sp-timestamp = {workspace = true}
sp-transaction-pool = {workspace = true}
substrate-frame-rpc-system = {workspace = true}
substrate-prometheus-endpoint = {workspace = true}
try-runtime-cli = {workspace = true}

# Polkadot
polkadot-cli = {workspace = true}
polkadot-parachain = {workspace = true}
polkadot-primitives = {workspace = true}
polkadot-service = {workspace = true}
xcm = {workspace = true, default-features = false}

# Cumulus
cumulus-client-cli = {workspace = true}
cumulus-client-collator = {workspace = true}
cumulus-client-consensus-aura = {workspace = true}
cumulus-client-consensus-common = {workspace = true}
cumulus-client-consensus-relay-chain = {workspace = true}
cumulus-client-network = {workspace = true}
cumulus-client-service = {workspace = true}
cumulus-primitives-core = {workspace = true}
cumulus-primitives-parachain-inherent = {workspace = true}
cumulus-relay-chain-inprocess-interface = {workspace = true}
cumulus-relay-chain-interface = {workspace = true}
cumulus-relay-chain-rpc-interface = {workspace = true}

# Runtime
gari-runtime = {path = "../../../runtime/gari", default-features = false, features = ["std"]}

# Local
gafi-support = {path = "../../../support"}

[features]
default = ["std"]
std = []
