[package]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a parachain."
homepage = "https://substrate.io"
license = "Unlicense"
name = "gafi-rpc"
version = "0.1.0"

publish = false
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0"}
derive_more = "0.99.2"
futures = '0.3'
jsonrpsee = { workspace = true, features = ["server", "macros"] }
log = "0.4.16"
serde = {version = "1.0.132", features = ["derive"]}

# Local
gafi-support = {path = "../../../support"}
gari-runtime = {path = "../../../runtime/gari"}

# Frontier
fc-db = {workspace = true}
fc-rpc = {workspace = true}
fc-rpc-core = {workspace = true}
fp-rpc = {workspace = true}
fp-storage = {workspace = true}

# Substrate
pallet-transaction-payment-rpc = {workspace = true}
sc-client-api = {workspace = true}
sc-consensus-aura = {workspace = true, optional = true}
sc-consensus-manual-seal = {workspace = true}
sc-network = {workspace = true}
sc-rpc = {workspace = true}
sc-rpc-api = {workspace = true}
sc-service = {workspace = true}
sc-transaction-pool = {workspace = true}
sc-transaction-pool-api = {workspace = true}
sp-api = {workspace = true}
sp-block-builder = {workspace = true}
sp-blockchain = {workspace = true}
sp-core = {workspace = true}
sp-runtime = {workspace = true}
substrate-frame-rpc-system = {workspace = true}

[build-dependencies]
substrate-build-script-utils = {workspace = true}

[features]
default = ["std"]
std = []
