[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
name = "runtime-common"
version = "0.9.23"

[dependencies]
impl-trait-for-tuples = "0.2.2"
log = {version = "0.4.17", default-features = false}
parity-scale-codec = {version = "3.1.2", default-features = false, features = ["derive"]}
rustc-hex = {version = "2.1.0", default-features = false}
scale-info = {version = "2.1.2", default-features = false, features = ["derive"]}
static_assertions = "1.1.0"

sp-core = {workspace = true}
sp-io = {workspace = true, default-features = false}
sp-runtime = {workspace = true}
sp-std = {package = "sp-std", workspace = true}

frame-support = {version = "4.0.0-dev", workspace = true}
frame-system = {version = "4.0.0-dev", workspace = true}
pallet-authorship = {workspace = true}
pallet-balances = {workspace = true}
pallet-treasury = {version = "4.0.0-dev", workspace = true}

frame-benchmarking = {version = "4.0.0-dev", workspace = true, optional = true}

[dev-dependencies]
pallet-treasury = {workspace = true}
sp-keystore = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42"}
trie-db = "0.23.1"

[features]
default = ["std"]
no_std = []
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
  "parity-scale-codec/std",
  "scale-info/std",
  "log/std",
  "rustc-hex/std",
  "sp-core/std",
  "sp-std/std",
  "sp-io/std",
  "frame-support/std",
  "pallet-treasury/std",
  "sp-runtime/std",
  "frame-system/std",
]
try-runtime = [
  # "pallet-transaction-payment/try-runtime",
  "pallet-treasury/try-runtime",
]
