[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "A fresh FRAME-based Substrate runtime, ready for hacking."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "devnet"
publish = false
repository = "https://github.com/grindytech/gafi"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
]}
log = {version = "0.4.17", default-features = false}
scale-info = {version = "2.1.0", default-features = false, features = [
  "derive",
]}
static_assertions = "1.1.0"

# Frontier
fp-rpc = {workspace = true}
fp-self-contained = {workspace = true}
pallet-base-fee = {workspace = true}
pallet-dynamic-fee = {workspace = true}
pallet-ethereum = {workspace = true}
pallet-evm = {workspace = true}
pallet-evm-precompile-modexp = {workspace = true}
pallet-evm-precompile-sha3fips = {workspace = true}
pallet-evm-precompile-simple = {workspace = true}
pallet-hotfix-sufficients = {workspace = true}

# Substrate
frame-executive = {workspace = true}
frame-support = {workspace = true}
frame-system = {workspace = true}
pallet-aura = {workspace = true}
pallet-balances = {workspace = true}
pallet-collective = {workspace = true}
pallet-democracy = {workspace = true}
pallet-elections-phragmen = {workspace = true}
pallet-grandpa = {workspace = true}
pallet-preimage = {workspace = true}
pallet-randomness-collective-flip = {workspace = true}
pallet-scheduler = {workspace = true}
pallet-sudo = {workspace = true}
pallet-timestamp = {workspace = true}
pallet-transaction-payment = {workspace = true}
pallet-treasury = {workspace = true}
sp-api = {workspace = true}
sp-block-builder = {workspace = true}
sp-consensus-aura = {workspace = true}
sp-core = {workspace = true}
sp-inherents = {workspace = true}
sp-io = {workspace = true}
sp-offchain = {workspace = true}
sp-runtime = {workspace = true}
sp-session = {workspace = true}
sp-std = {workspace = true}
sp-transaction-pool = {workspace = true}
sp-version = {workspace = true}

# Used for the node template's RPCs
frame-system-rpc-runtime-api = {workspace = true}
pallet-transaction-payment-rpc-runtime-api = {workspace = true}

# Used for runtime benchmarking
frame-benchmarking = {workspace = true, optional = true}
frame-system-benchmarking = {workspace = true, optional = true}
hex-literal = {version = "0.3.4", optional = true}

# Local Dependencies
gafi-primitives = {version = "4.0.0-dev", default-features = false, path = "../../primitives"}
runtime-common = {package = "runtime-common", path = "../common", default-features = false}

# Local pallets
funding-pool = {version = "4.0.0-dev", default-features = false, path = "../../pallets/funding-pool"}
gafi-tx = {version = "4.0.0-dev", default-features = false, path = "../../pallets/gafi-tx"}
game-creator = {version = "4.0.0-dev", default-features = false, path = "../../pallets/game-creator"}
pallet-cache = {version = "4.0.0-dev", default-features = false, path = "../../pallets/pallet-cache"}
pallet-faucet = {version = "4.0.0-dev", default-features = false, path = "../../pallets/pallet-faucet"}
pallet-player = {version = "4.0.0-dev", default-features = false, path = "../../pallets/player"}
pallet-player-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, path = "../../pallets/player/runtime-api"}
pallet-pool = {version = "4.0.0-dev", default-features = false, path = "../../pallets/pool"}
pallet-pool-names = {version = "4.0.0-dev", default-features = false, path = "../../pallets/pool-names"}
pallet-whitelist = {version = "4.0.0-dev", default-features = false, path = "../../pallets/whitelist"}
proof-address-mapping = {version = "4.0.0-dev", default-features = false, path = "../../pallets/address-mapping"}
staking-pool = {version = "4.0.0-dev", default-features = false, path = "../../pallets/staking-pool"}
upfront-pool = {version = "4.0.0-dev", default-features = false, path = "../../pallets/upfront-pool"}

# unit test
[dev.dependencies]
sp-io = {workspace = true}

[build-dependencies]
substrate-wasm-builder = {version = "5.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37"}

[features]
aura = []
default = ["std", "aura", "with-rocksdb-weights"]
manual-seal = ["with-rocksdb-weights"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "hex-literal",
  "pallet-balances/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "pallet-collective/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "pallet-ethereum/runtime-benchmarks",
  "pallet-evm/runtime-benchmarks",
  "upfront-pool/runtime-benchmarks",
  "staking-pool/runtime-benchmarks",
  "pallet-pool/runtime-benchmarks",
  "gafi-tx/runtime-benchmarks",
  "proof-address-mapping/runtime-benchmarks",
  "pallet-faucet/runtime-benchmarks",
  "funding-pool/runtime-benchmarks",
  "game-creator/runtime-benchmarks",
  "pallet-hotfix-sufficients/runtime-benchmarks",
  "pallet-whitelist/runtime-benchmarks",
]
std = [
  "codec/std",
  "scale-info/std",
  "frame-executive/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-randomness-collective-flip/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "pallet-treasury/std",
  "pallet-collective/std",
  "pallet-democracy/std",
  "pallet-scheduler/std",
  "pallet-preimage/std",
  "pallet-elections-phragmen/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  'pallet-evm/std',
  'pallet-ethereum/std',
  'fp-self-contained/std',
  'fp-rpc/std',
  'pallet-base-fee/std',
  "pallet-dynamic-fee/std",
  "pallet-evm-precompile-simple/std",
  "pallet-evm-precompile-sha3fips/std",
  "upfront-pool/std",
  "staking-pool/std",
  "gafi-tx/std",
  "gafi-primitives/std",
  "proof-address-mapping/std",
  "pallet-faucet/std",
  "pallet-pool/std",
  "pallet-cache/std",
  "funding-pool/std",
  "game-creator/std",
  "pallet-pool-names/std",
  "runtime-common/std",
  "pallet-hotfix-sufficients/std",
  "pallet-whitelist/std",
  "log/std",
]
with-dev = []
with-rocksdb-weights = []

# Set timing constants (e.g. session period) to faster versions to speed up testing.
fast-runtime = []
