[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "FRAME pallet template for defining custom runtime logic."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "pallet-pool"
publish = false
repository = "https://github.com/grindytech/gafi"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
] }
log = { version = "0.4.16" }
scale-info = { version = "2.1.0", default-features = false, features = [
  "derive",
] }
serde = { version = "1.0.119" }

# Substrate
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-timestamp = { workspace = true }
sp-io = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }

# Local
gafi-primitives = { version = "4.0.0-dev", default-features = false, path = "../../primitives" }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }
pallet-balances = { workspace = true }
pallet-randomness-collective-flip = { workspace = true }
pallet-nicks = {workspace = true}
staking-pool = { version = "4.0.0-dev", default-features = false, path = "../staking-pool" }
upfront-pool = { version = "4.0.0-dev", default-features = false, path = "../upfront-pool" }
funding-pool = { version = "4.0.0-dev", default-features = false, path = "../funding-pool" }
pallet-cache = { default-features = false, version = "4.0.0-dev", path = "../pallet-cache" }
gu-mock = { default-features = false, version = "4.0.0-dev", path = "../../utils/mock" }


[features]
default = ["std"]
std = [
  "codec/std",
  "scale-info/std",
  "serde/std",
  "frame-support/std",
  "frame-system/std",
  "gafi-primitives/std",
  "sp-std/std",
  "sp-io/std",
  "pallet-timestamp/std",
  "sp-core/std",
  "pallet-balances/std",
  "upfront-pool/std",
  "staking-pool/std",
  "funding-pool/std",
  "pallet-randomness-collective-flip/std",
]

runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "gafi-primitives/runtime-benchmarks",
  "funding-pool/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
