[package]
edition = {workspace = true}
name = "gu-convertor"
version = "4.0.0-dev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = {package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"]}
rustc-hex = {version = "2.1.0", default-features = false}
scale-info = {version = "2.5.0", default-features = false, features = ["derive"]}
serde = {workspace = true, features = ["derive"]}
sha3 = {version = "0.10", default-features = false}

# Substrate
frame-support = {default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"}
sp-core = {workspace = true, default-features = false}
sp-io = {workspace = true, default-features = false}
sp-runtime = {workspace = true, default-features = false}
sp-std = {workspace = true, default-features = false}

# Local
gafi-support = {default-features = false, version = "4.0.0-dev", path = "../../support"}

[dev-dependencies]
hex-literal = "0.2.1"
parity-secp256k1 = {default-features = false, version = "0.7.0", git = "https://github.com/paritytech/rust-secp256k1"}
pallet-balances = {default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0"}

[features]
default = ["std"]
std = [
  "sp-runtime/std",
  "sp-io/std",
  "sp-core/std",
  "sha3/std",
  "scale-info/std",
  "codec/std",
  "serde/std",
  "rustc-hex/std",
  "sp-std/std",
  "frame-support/std",
  "gafi-support/std",
  "pallet-balances/std",
]
