[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "node-template-runtime"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"]}
scale-info = {version = "2.1.1", default-features = false, features = ["derive"]}

frame-executive = {workspace = true, default-features = false}
frame-support = {workspace = true, default-features = false}
frame-system = {workspace = true, default-features = false}
frame-try-runtime = {workspace = true, default-features = false, optional = true}
pallet-aura = {workspace = true, default-features = false}
pallet-balances = {workspace = true, default-features = false}
pallet-grandpa = {workspace = true, default-features = false}
pallet-randomness-collective-flip = {workspace = true, default-features = false}
pallet-sudo = {workspace = true, default-features = false}
pallet-timestamp = {workspace = true, default-features = false}
pallet-transaction-payment = {workspace = true, default-features = false}
sp-api = {workspace = true, default-features = false}
sp-block-builder = {workspace = true, default-features = false}
sp-consensus-aura = {workspace = true, default-features = false}
sp-core = {workspace = true, default-features = false}
sp-inherents = {workspace = true, default-features = false}
sp-offchain = {workspace = true, default-features = false}
sp-runtime = {workspace = true, default-features = false}
sp-session = {workspace = true, default-features = false}
sp-std = {workspace = true, default-features = false}
sp-transaction-pool = {workspace = true, default-features = false}
sp-version = {workspace = true, default-features = false}

# Used for the node template's RPCs
frame-system-rpc-runtime-api = {workspace = true, default-features = false}
pallet-transaction-payment-rpc-runtime-api = {workspace = true, default-features = false}

# Used for runtime benchmarking
frame-benchmarking = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, optional = true, branch = "polkadot-v0.9.37"}
frame-system-benchmarking = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, optional = true, branch = "polkadot-v0.9.37"}

# Local Dependencies

[build-dependencies]
substrate-wasm-builder = {version = "5.0.0-dev", git = "https://github.com/paritytech/substrate.git", optional = true, branch = "polkadot-v0.9.37"}

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
std = [
  "frame-try-runtime?/std",
  "frame-system-benchmarking?/std",
  "frame-benchmarking?/std",
  "codec/std",
  "scale-info/std",
  "frame-executive/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "frame-try-runtime/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-randomness-collective-flip/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "substrate-wasm-builder",
]
try-runtime = [
  "frame-try-runtime/try-runtime",
  "frame-executive/try-runtime",
  "frame-system/try-runtime",
  "frame-support/try-runtime",
  "pallet-aura/try-runtime",
  "pallet-balances/try-runtime",
  "pallet-grandpa/try-runtime",
  "pallet-randomness-collective-flip/try-runtime",
  "pallet-sudo/try-runtime",
  "pallet-timestamp/try-runtime",
  "pallet-transaction-payment/try-runtime",
]
