[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition = "2021"
homepage = "https://substrate.io/"
license = "Apache-2.0"
name = "game3-runtime"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = {version = "0.4.19", default-features = false}
codec = {package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"]}
scale-info = {version = "2.8.0", default-features = false, features = ["derive"]}

frame-executive = {default-features = false, workspace = true}
frame-support = {default-features = false, workspace = true}
frame-system = {default-features = false, workspace = true}
frame-try-runtime = {workspace = true, default-features = false, optional = true}
pallet-aura = {default-features = false, workspace = true}
pallet-balances = {default-features = false, workspace = true}
pallet-grandpa = {default-features = false, workspace = true}
pallet-insecure-randomness-collective-flip = {workspace = true, default-features = false}
pallet-nfts = {default-features = false, workspace = true}
pallet-sudo = {default-features = false, workspace = true}
pallet-timestamp = {default-features = false, workspace = true}
pallet-transaction-payment = {default-features = false, workspace = true}
sp-api = {default-features = false, workspace = true}
sp-block-builder = {default-features = false, workspace = true}
sp-consensus-aura = {default-features = false, workspace = true}
sp-consensus-grandpa = {default-features = false, workspace = true}
sp-core = {default-features = false, workspace = true}
sp-inherents = {default-features = false, workspace = true}
sp-offchain = {default-features = false, workspace = true}
sp-runtime = {default-features = false, workspace = true}
sp-session = {default-features = false, workspace = true}
sp-std = {default-features = false, workspace = true}
sp-transaction-pool = {default-features = false, workspace = true}
sp-version = {default-features = false, workspace = true}

# Used for the node template's RPCs
frame-system-rpc-runtime-api = {workspace = true, default-features = false}
pallet-transaction-payment-rpc-runtime-api = {workspace = true, default-features = false}

# Used for runtime benchmarking
frame-benchmarking = {workspace = true, default-features = false, optional = true}
frame-system-benchmarking = {workspace = true, default-features = false, optional = true}

# Local Dependencies
gafi-support = {version = "4.0.0-dev", default-features = false, path = "../../support"}
pallet-cache = {version = "4.0.0-dev", default-features = false, path = "../../pallets/pallet-cache"}
pallet-faucet = {version = "4.0.0-dev", default-features = false, path = "../../pallets/pallet-faucet"}
pallet-template = {version = "4.0.0-dev", default-features = false, path = "../../pallets/template"}

pallet-game = {version = "4.0.0-dev", default-features = false, path = "../../game/pallet-game"}

[build-dependencies]
substrate-wasm-builder = {workspace = true, optional = true}

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "pallet-faucet/runtime-benchmarks",
  "pallet-nfts/runtime-benchmarks",
  "pallet-game/runtime-benchmarks"
]
std = [
  "frame-try-runtime?/std",
  "frame-system-benchmarking?/std",
  "frame-benchmarking?/std",
  "codec/std",
  "scale-info/std",
  "frame-executive/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "frame-try-runtime/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-insecure-randomness-collective-flip/std",
  "pallet-transaction-payment/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-consensus-grandpa/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "substrate-wasm-builder",
  "pallet-faucet/std",
  "pallet-cache/std",
  "gafi-support/std",
  "pallet-template/std",
  "pallet-nfts/std",
  "pallet-game/std",
]
try-runtime = [
  "frame-try-runtime/try-runtime",
  "frame-executive/try-runtime",
  "frame-system/try-runtime",
  "frame-support/try-runtime",
  "pallet-aura/try-runtime",
  "pallet-balances/try-runtime",
  "pallet-grandpa/try-runtime",
  "pallet-sudo/try-runtime",
  "pallet-timestamp/try-runtime",
  "pallet-transaction-payment/try-runtime",
  "gafi-support/try-runtime",
  "pallet-template/try-runtime",
  "pallet-cache/try-runtime",
  "pallet-faucet/try-runtime",
  "pallet-nfts/try-runtime",
  "pallet-game/try-runtime",
]

with-game3 = []
