name: Check Set-Up & Build

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install linux dependencies
        run: sudo apt-get install -y clang libssl-dev llvm libudev-dev protobuf-compiler

      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup target add wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install make
        run: sudo apt-get install -y make

      - name: Unit-Test
        run: make test

      - name: Check Build
        run: make check

      - name: Check Build for Benchmarking
        run: |
          mkdir node  # Create the "node" directory
          pushd node
          make check-benchmark
          popd  # Return to the previous directory
